apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: ontap-san-backend
  namespace: trident
spec:
  version: 1
  backendName: san-backend-iscsi
  storageDriverName: ontap-san
  santype: iscsi
  managementLIF: 172.24.32.33
  defaults:
    nameTemplate: "{{ .volume.Name }}_{{ .volume.Namespace }}_{{ .volume.RequestName }}"
  svm: PM_trident_K8s
  credentials:
    name: ontap-nas-secret