apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-ontap-nas
  namespace: <tridentnamespace>
spec:
  version: 1
  backendName: backend-nas
  useRest: false
  storageDriverName: ontap-nas
  managementLIF: <ip of svm mgmt lif>
  autoExportCIDRs:
    - <ip subnet of k8s nodes>
  autoExportPolicy: true
  defaults:
    nameTemplate: "{{ .volume.Name }}_{{ .volume.Namespace }}_{{ .volume.RequestName }}"
  credentials:
    name: secret-svm
