defaults {
    user_friendly_names no
    find_multipaths no
}

            blacklist {
    device {
        vendor “!NETAPP”
        product “!LUN”
    }
}

            blacklist_exceptions {
    device {
        vendor “NETAPP”
        product “LUN”
    }
}