apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-ontap-san-nvme
  namespace: <tridentnamespace>
spec:
  version: 1
  backendName: san-nvme
# nvme only supports ontap-san today, no economy driver possible.
  storageDriverName: ontap-san
  sanType: nvme
# nvme is not working via ZAPI, we need to enforce the usage of REST
  useREST: true
  managementLIF: <ip of svm mgmt lif>
  defaults:
    nameTemplate: "{{ .volume.Name }}_{{ .volume.Namespace }}_{{ .volume.RequestName }}"
  credentials:
    name: secret-svm
